### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by selroc** [tdulcet/Distributed-Computing-Scripts#11]
'primenet.py: send_progress: Tue 02 Nov 2021 03:40:48 AM CET     Cannot update, the registration is not done'

which parameters needed for registration ?

**Comment by tdulcet** [comment]
> which parameters needed for registration ?

You can run the `--help` option to see all of the registering parameters, although they are all optional. It automatically registers the computer with PrimeNet if the user does _NOT_ provide a password.

I believe the issue is that you provided your password, which restricts the script to manual testing, the default behavior for old versions of this script. To fix the issue, just open your `local.ini` file and delete the `password =` line.

**Comment by selroc** [comment]
> > which parameters needed for registration ?
> 
> You can run the `--help` option to see all of the registering parameters, although they are all optional. It automatically registers the computer with PrimeNet if the user does _NOT_ provide a password.
> 
> I believe the issue is that you provided your password, which restricts the script to manual testing, the default behavior for old versions of this script. To fix the issue, just open your `local.ini` file and delete the `password =` line.

Yes this worked, thank you.
