### ISSUE TITLE
mlucas.sh fails on Fedora 40 Asahi Remix, M2 processor

### ISSUE THREAD

**Issue by proski** [tdulcet/Distributed-Computing-Scripts#23]
The output of `lspcu` on M2 CPU contains `Thread(s) per core` twice. As a result, the `HP` variable has a newline in it: `1\n1`. That leads to many error messages in the script (some are very confusing). A workaround is to apply `sort -u` to the sed output in the HP assignment, but it would still break if the values are different. Perhaps the newline can be detected and reported. I'm attaching the complete output of `lscpu`.
[lscpu-out.txt](https://github.com/user-attachments/files/15524283/lscpu-out.txt)

**Comment by tdulcet** [comment]
Thank you for the bug report and the `lscpu` output. I did not realize that `Thread(s) per core` could be output more than once. The solution is to select the largest value with `sort -nr | head -n 1`. I will update the script to do this.

For future reference, you could run Bash with the `-e` option so that it exits after the first error:
`bash -e -o pipefail -- mlucas.sh [...]`
